export const DEFAULT_BUDGET_CATEGORIES = [
  { code: '1 - PRELIMINARES', name: 'Preliminares', sort_order: 1 },
  { code: '2 - DEMOLICIONES', name: 'Demoliciones', sort_order: 2 },
  { code: '3 - ESTRUCTURA', name: 'Estructura', sort_order: 3 },
  { code: '4 - H.A.', name: 'Hormigón armado', sort_order: 4 },
  { code: '5 - MUROS', name: 'Muros', sort_order: 5 },
  { code: '6 - TERMINACION DE SUPERFICIE', name: 'Terminación de superficie', sort_order: 6 },
  { code: '7 - PLAFON', name: 'Plafón', sort_order: 7 },
  { code: '8 - PLOMERIA', name: 'Plomería', sort_order: 8 },
  { code: '9 - TECHOS', name: 'Techos', sort_order: 9 },
  { code: '10 - PISOS', name: 'Pisos', sort_order: 10 },
  { code: '11 - REVESTIMIENTOS', name: 'Revestimientos', sort_order: 11 },
  { code: '12 - ESCALERAS', name: 'Escaleras', sort_order: 12 },
  { code: '13 - INST. ELECTRICA', name: 'Instalación eléctrica', sort_order: 13 },
  { code: '14 - INST. SANITARIA', name: 'Instalación sanitaria', sort_order: 14 },
  { code: '15 - HERRERIA', name: 'Herrería', sort_order: 15 },
  { code: '16 - PORTAJE', name: 'Portaje', sort_order: 16 },
  { code: '17 - VENTANAS', name: 'Ventanas', sort_order: 17 },
  { code: '18 - PINTURA', name: 'Pintura', sort_order: 18 },
  { code: '19 - DEPOSITOS', name: 'Depósitos', sort_order: 19 },
  { code: '20 - EQUIPAMIENTO', name: 'Equipamiento', sort_order: 20 },
  { code: '21 - CERRAJERIA', name: 'Cerrajería', sort_order: 21 },
  { code: '22 - MISCELANEOS', name: 'Misceláneos', sort_order: 22 },
  { code: '23 - GASTOS INDIRECTOS', name: 'Gastos indirectos', sort_order: 23 },
] as const
