// Auto-generated by Supabase MCP. Do not edit manually.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      adjustment_contracts: {
        Row: {
          contractor_id: string
          created_at: string | null
          id: string
          notes: string | null
          project_id: string
          retention_percent: number
          signed_date: string | null
        }
        Insert: {
          contractor_id: string
          created_at?: string | null
          id?: string
          notes?: string | null
          project_id: string
          retention_percent?: number
          signed_date?: string | null
        }
        Update: {
          contractor_id?: string
          created_at?: string | null
          id?: string
          notes?: string | null
          project_id?: string
          retention_percent?: number
          signed_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "adjustment_contracts_contractor_id_fkey"
            columns: ["contractor_id"]
            isOneToOne: false
            referencedRelation: "contractors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "adjustment_contracts_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      approvals: {
        Row: {
          action: string
          actor_display_name: string | null
          actor_user_id: string | null
          created_at: string
          entity_id: string
          entity_type: string
          id: string
          metadata: Json
          motivo: string | null
          payload_after: Json | null
          payload_before: Json | null
        }
        Insert: {
          action: string
          actor_display_name?: string | null
          actor_user_id?: string | null
          created_at?: string
          entity_id: string
          entity_type: string
          id?: string
          metadata?: Json
          motivo?: string | null
          payload_after?: Json | null
          payload_before?: Json | null
        }
        Update: {
          action?: string
          actor_display_name?: string | null
          actor_user_id?: string | null
          created_at?: string
          entity_id?: string
          entity_type?: string
          id?: string
          metadata?: Json
          motivo?: string | null
          payload_after?: Json | null
          payload_before?: Json | null
        }
        Relationships: []
      }
      attendance_records: {
        Row: {
          activity: string
          contractor_id: string
          created_at: string | null
          date: string
          hours_worked: number
          id: string
          latitude: number | null
          longitude: number | null
          notes: string | null
          photo_url: string | null
          project_id: string
          workers_count: number
        }
        Insert: {
          activity: string
          contractor_id: string
          created_at?: string | null
          date: string
          hours_worked?: number
          id?: string
          latitude?: number | null
          longitude?: number | null
          notes?: string | null
          photo_url?: string | null
          project_id: string
          workers_count?: number
        }
        Update: {
          activity?: string
          contractor_id?: string
          created_at?: string | null
          date?: string
          hours_worked?: number
          id?: string
          latitude?: number | null
          longitude?: number | null
          notes?: string | null
          photo_url?: string | null
          project_id?: string
          workers_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "attendance_records_contractor_id_fkey"
            columns: ["contractor_id"]
            isOneToOne: false
            referencedRelation: "contractors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendance_records_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      bank_accounts: {
        Row: {
          account_number: string
          account_type: string | null
          bank_name: string
          cedula_rnc: string | null
          id: string
          is_internal: boolean
          owner_name: string
          project_id: string | null
        }
        Insert: {
          account_number: string
          account_type?: string | null
          bank_name: string
          cedula_rnc?: string | null
          id?: string
          is_internal?: boolean
          owner_name: string
          project_id?: string | null
        }
        Update: {
          account_number?: string
          account_type?: string | null
          bank_name?: string
          cedula_rnc?: string | null
          id?: string
          is_internal?: boolean
          owner_name?: string
          project_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bank_accounts_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      bitacora_entries: {
        Row: {
          created_at: string | null
          created_by: string
          date: string
          equipment: string | null
          id: string
          incidents: string | null
          notes: string | null
          project_id: string
          temp_c: number | null
          visitors: string | null
          weather: string
          work_summary: string
          workforce_count: number
        }
        Insert: {
          created_at?: string | null
          created_by: string
          date: string
          equipment?: string | null
          id?: string
          incidents?: string | null
          notes?: string | null
          project_id: string
          temp_c?: number | null
          visitors?: string | null
          weather: string
          work_summary: string
          workforce_count?: number
        }
        Update: {
          created_at?: string | null
          created_by?: string
          date?: string
          equipment?: string | null
          id?: string
          incidents?: string | null
          notes?: string | null
          project_id?: string
          temp_c?: number | null
          visitors?: string | null
          weather?: string
          work_summary?: string
          workforce_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "bitacora_entries_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      budget_categories: {
        Row: {
          budgeted_amount: number
          code: string
          end_date: string | null
          id: string
          name: string
          project_id: string
          sort_order: number
          start_date: string | null
        }
        Insert: {
          budgeted_amount?: number
          code: string
          end_date?: string | null
          id?: string
          name: string
          project_id: string
          sort_order?: number
          start_date?: string | null
        }
        Update: {
          budgeted_amount?: number
          code?: string
          end_date?: string | null
          id?: string
          name?: string
          project_id?: string
          sort_order?: number
          start_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "budget_categories_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      budget_items: {
        Row: {
          budget_category_id: string
          code: string | null
          description: string
          end_date: string | null
          id: string
          notes: string | null
          quantity: number
          sort_order: number
          start_date: string | null
          unit: string
          unit_price: number
        }
        Insert: {
          budget_category_id: string
          code?: string | null
          description: string
          end_date?: string | null
          id?: string
          notes?: string | null
          quantity?: number
          sort_order?: number
          start_date?: string | null
          unit: string
          unit_price?: number
        }
        Update: {
          budget_category_id?: string
          code?: string | null
          description?: string
          end_date?: string | null
          id?: string
          notes?: string | null
          quantity?: number
          sort_order?: number
          start_date?: string | null
          unit?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "budget_items_budget_category_id_fkey"
            columns: ["budget_category_id"]
            isOneToOne: false
            referencedRelation: "budget_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      budget_versions: {
        Row: {
          actor: string | null
          created_at: string
          id: string
          motivo: string
          project_id: string
          snapshot: Json
          version: number
        }
        Insert: {
          actor?: string | null
          created_at?: string
          id?: string
          motivo: string
          project_id: string
          snapshot: Json
          version: number
        }
        Update: {
          actor?: string | null
          created_at?: string
          id?: string
          motivo?: string
          project_id?: string
          snapshot?: Json
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "budget_versions_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      capabilities: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          scope: string
          section: string
          slug: string
          sort_order: number
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          scope: string
          section: string
          slug: string
          sort_order?: number
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          scope?: string
          section?: string
          slug?: string
          sort_order?: number
        }
        Relationships: []
      }
      companies: {
        Row: {
          created_at: string | null
          id: string
          name: string
          rnc: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          name: string
          rnc?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          name?: string
          rnc?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      contract_adelantos: {
        Row: {
          advance_date: string
          amount: number
          contract_id: string
          created_at: string | null
          description: string | null
          id: string
        }
        Insert: {
          advance_date: string
          amount?: number
          contract_id: string
          created_at?: string | null
          description?: string | null
          id?: string
        }
        Update: {
          advance_date?: string
          amount?: number
          contract_id?: string
          created_at?: string | null
          description?: string | null
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "contract_adelantos_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "adjustment_contracts"
            referencedColumns: ["id"]
          },
        ]
      }
      contract_cortes: {
        Row: {
          amount: number
          approved_by: string | null
          contract_id: string
          created_at: string | null
          cut_date: string
          cut_number: number
          id: string
          linked_payroll_id: string | null
          measured_quantity: number
          notes: string | null
          partida_id: string
          photo_url: string | null
          retention_amount: number
          signature_data: string | null
          status: string
        }
        Insert: {
          amount?: number
          approved_by?: string | null
          contract_id: string
          created_at?: string | null
          cut_date: string
          cut_number?: number
          id?: string
          linked_payroll_id?: string | null
          measured_quantity?: number
          notes?: string | null
          partida_id: string
          photo_url?: string | null
          retention_amount?: number
          signature_data?: string | null
          status?: string
        }
        Update: {
          amount?: number
          approved_by?: string | null
          contract_id?: string
          created_at?: string | null
          cut_date?: string
          cut_number?: number
          id?: string
          linked_payroll_id?: string | null
          measured_quantity?: number
          notes?: string | null
          partida_id?: string
          photo_url?: string | null
          retention_amount?: number
          signature_data?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "contract_cortes_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "adjustment_contracts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contract_cortes_linked_payroll_id_fkey"
            columns: ["linked_payroll_id"]
            isOneToOne: false
            referencedRelation: "payroll_periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contract_cortes_partida_id_fkey"
            columns: ["partida_id"]
            isOneToOne: false
            referencedRelation: "contract_partidas"
            referencedColumns: ["id"]
          },
        ]
      }
      contract_cubications: {
        Row: {
          adjusted_budget: number | null
          completion_percent: number
          contractor_id: string
          id: string
          original_budget: number | null
          project_id: string
          remaining: number
          specialty: string
          total_advanced: number
        }
        Insert: {
          adjusted_budget?: number | null
          completion_percent?: number
          contractor_id: string
          id?: string
          original_budget?: number | null
          project_id: string
          remaining?: number
          specialty: string
          total_advanced?: number
        }
        Update: {
          adjusted_budget?: number | null
          completion_percent?: number
          contractor_id?: string
          id?: string
          original_budget?: number | null
          project_id?: string
          remaining?: number
          specialty?: string
          total_advanced?: number
        }
        Relationships: [
          {
            foreignKeyName: "contract_cubications_contractor_id_fkey"
            columns: ["contractor_id"]
            isOneToOne: false
            referencedRelation: "contractors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contract_cubications_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      contract_partidas: {
        Row: {
          agreed_quantity: number
          contract_id: string
          description: string
          id: string
          sort_order: number
          unit: string
          unit_price: number
        }
        Insert: {
          agreed_quantity?: number
          contract_id: string
          description: string
          id?: string
          sort_order?: number
          unit: string
          unit_price?: number
        }
        Update: {
          agreed_quantity?: number
          contract_id?: string
          description?: string
          id?: string
          sort_order?: number
          unit?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "contract_partidas_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "adjustment_contracts"
            referencedColumns: ["id"]
          },
        ]
      }
      contractor_documents: {
        Row: {
          contractor_id: string
          created_at: string | null
          doc_type: string
          expiry_date: string | null
          file_ref: string | null
          id: string
          name: string
          notes: string | null
          status: string
        }
        Insert: {
          contractor_id: string
          created_at?: string | null
          doc_type: string
          expiry_date?: string | null
          file_ref?: string | null
          id?: string
          name: string
          notes?: string | null
          status?: string
        }
        Update: {
          contractor_id?: string
          created_at?: string | null
          doc_type?: string
          expiry_date?: string | null
          file_ref?: string | null
          id?: string
          name?: string
          notes?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "contractor_documents_contractor_id_fkey"
            columns: ["contractor_id"]
            isOneToOne: false
            referencedRelation: "contractors"
            referencedColumns: ["id"]
          },
        ]
      }
      contractor_loans: {
        Row: {
          contractor_id: string
          created_at: string | null
          disbursed_date: string
          id: string
          installment_amount: number
          installments: number
          interest_rate: number
          notes: string | null
          principal: number
          status: string
        }
        Insert: {
          contractor_id: string
          created_at?: string | null
          disbursed_date: string
          id?: string
          installment_amount?: number
          installments?: number
          interest_rate?: number
          notes?: string | null
          principal?: number
          status?: string
        }
        Update: {
          contractor_id?: string
          created_at?: string | null
          disbursed_date?: string
          id?: string
          installment_amount?: number
          installments?: number
          interest_rate?: number
          notes?: string | null
          principal?: number
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "contractor_loans_contractor_id_fkey"
            columns: ["contractor_id"]
            isOneToOne: false
            referencedRelation: "contractors"
            referencedColumns: ["id"]
          },
        ]
      }
      contractors: {
        Row: {
          bank_account: string | null
          bank_name: string | null
          cedula: string | null
          created_at: string | null
          hierarchy_level: number
          id: string
          is_active: boolean
          name: string
          notes: string | null
          parent_contractor_id: string | null
          payment_method: string
          phone: string | null
          specialty: string | null
          updated_at: string | null
        }
        Insert: {
          bank_account?: string | null
          bank_name?: string | null
          cedula?: string | null
          created_at?: string | null
          hierarchy_level?: number
          id?: string
          is_active?: boolean
          name: string
          notes?: string | null
          parent_contractor_id?: string | null
          payment_method?: string
          phone?: string | null
          specialty?: string | null
          updated_at?: string | null
        }
        Update: {
          bank_account?: string | null
          bank_name?: string | null
          cedula?: string | null
          created_at?: string | null
          hierarchy_level?: number
          id?: string
          is_active?: boolean
          name?: string
          notes?: string | null
          parent_contractor_id?: string | null
          payment_method?: string
          phone?: string | null
          specialty?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contractors_parent_contractor_id_fkey"
            columns: ["parent_contractor_id"]
            isOneToOne: false
            referencedRelation: "contractors"
            referencedColumns: ["id"]
          },
        ]
      }
      expected_cash_inflows: {
        Row: {
          amount: number
          concept: string
          created_at: string
          created_by: string | null
          expected_date: string
          external_ref: string | null
          id: string
          notes: string | null
          project_id: string
          source: string
        }
        Insert: {
          amount?: number
          concept: string
          created_at?: string
          created_by?: string | null
          expected_date: string
          external_ref?: string | null
          id?: string
          notes?: string | null
          project_id: string
          source?: string
        }
        Update: {
          amount?: number
          concept?: string
          created_at?: string
          created_by?: string | null
          expected_date?: string
          external_ref?: string | null
          id?: string
          notes?: string | null
          project_id?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "expected_cash_inflows_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      indirect_costs: {
        Row: {
          base_amount: number | null
          calculated_amount: number
          description: string | null
          fixed_amount: number | null
          id: string
          is_active: boolean
          notes: string | null
          payroll_period_id: string
          percentage: number | null
          type: string
        }
        Insert: {
          base_amount?: number | null
          calculated_amount?: number
          description?: string | null
          fixed_amount?: number | null
          id?: string
          is_active?: boolean
          notes?: string | null
          payroll_period_id: string
          percentage?: number | null
          type: string
        }
        Update: {
          base_amount?: number | null
          calculated_amount?: number
          description?: string | null
          fixed_amount?: number | null
          id?: string
          is_active?: boolean
          notes?: string | null
          payroll_period_id?: string
          percentage?: number | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "indirect_costs_payroll_period_id_fkey"
            columns: ["payroll_period_id"]
            isOneToOne: false
            referencedRelation: "payroll_periods"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_items: {
        Row: {
          created_at: string | null
          current_stock: number
          id: string
          material_catalog_id: string | null
          min_stock: number
          name: string
          project_id: string
          unit: string
          unit_cost: number
        }
        Insert: {
          created_at?: string | null
          current_stock?: number
          id?: string
          material_catalog_id?: string | null
          min_stock?: number
          name: string
          project_id: string
          unit: string
          unit_cost?: number
        }
        Update: {
          created_at?: string | null
          current_stock?: number
          id?: string
          material_catalog_id?: string | null
          min_stock?: number
          name?: string
          project_id?: string
          unit?: string
          unit_cost?: number
        }
        Relationships: [
          {
            foreignKeyName: "inventory_items_material_catalog_id_fkey"
            columns: ["material_catalog_id"]
            isOneToOne: false
            referencedRelation: "materials_catalog"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_items_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_lots: {
        Row: {
          created_at: string
          expiry_date: string | null
          id: string
          item_id: string
          lot_number: string | null
          notes: string | null
          quantity: number
          received_date: string
          unit_cost: number | null
        }
        Insert: {
          created_at?: string
          expiry_date?: string | null
          id?: string
          item_id: string
          lot_number?: string | null
          notes?: string | null
          quantity?: number
          received_date?: string
          unit_cost?: number | null
        }
        Update: {
          created_at?: string
          expiry_date?: string | null
          id?: string
          item_id?: string
          lot_number?: string | null
          notes?: string | null
          quantity?: number
          received_date?: string
          unit_cost?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "inventory_lots_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "inventory_items"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_movements: {
        Row: {
          budget_category_id: string | null
          budget_item_id: string | null
          created_at: string | null
          created_by: string | null
          date: string
          id: string
          item_id: string
          lot_id: string | null
          notes: string | null
          override_motivo: string | null
          project_id: string
          purchase_order_id: string | null
          quantity: number
          supplier_id: string | null
          type: string
          unit_cost: number | null
        }
        Insert: {
          budget_category_id?: string | null
          budget_item_id?: string | null
          created_at?: string | null
          created_by?: string | null
          date: string
          id?: string
          item_id: string
          lot_id?: string | null
          notes?: string | null
          override_motivo?: string | null
          project_id: string
          purchase_order_id?: string | null
          quantity?: number
          supplier_id?: string | null
          type: string
          unit_cost?: number | null
        }
        Update: {
          budget_category_id?: string | null
          budget_item_id?: string | null
          created_at?: string | null
          created_by?: string | null
          date?: string
          id?: string
          item_id?: string
          lot_id?: string | null
          notes?: string | null
          override_motivo?: string | null
          project_id?: string
          purchase_order_id?: string | null
          quantity?: number
          supplier_id?: string | null
          type?: string
          unit_cost?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "inventory_movements_budget_category_id_fkey"
            columns: ["budget_category_id"]
            isOneToOne: false
            referencedRelation: "budget_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_budget_item_id_fkey"
            columns: ["budget_item_id"]
            isOneToOne: false
            referencedRelation: "budget_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "inventory_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_lot_id_fkey"
            columns: ["lot_id"]
            isOneToOne: false
            referencedRelation: "inventory_lots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_requisitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      labor_line_items: {
        Row: {
          budget_category_id: string | null
          budget_item_id: string | null
          contractor_id: string
          description: string
          id: string
          is_advance: boolean
          is_advance_deduction: boolean
          notes: string | null
          payroll_period_id: string
          quantity: number
          sort_order: number
          subtotal: number
          unit: string
          unit_price: number
        }
        Insert: {
          budget_category_id?: string | null
          budget_item_id?: string | null
          contractor_id: string
          description: string
          id?: string
          is_advance?: boolean
          is_advance_deduction?: boolean
          notes?: string | null
          payroll_period_id: string
          quantity?: number
          sort_order?: number
          subtotal?: number
          unit: string
          unit_price?: number
        }
        Update: {
          budget_category_id?: string | null
          budget_item_id?: string | null
          contractor_id?: string
          description?: string
          id?: string
          is_advance?: boolean
          is_advance_deduction?: boolean
          notes?: string | null
          payroll_period_id?: string
          quantity?: number
          sort_order?: number
          subtotal?: number
          unit?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "labor_line_items_budget_category_id_fkey"
            columns: ["budget_category_id"]
            isOneToOne: false
            referencedRelation: "budget_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "labor_line_items_budget_item_id_fkey"
            columns: ["budget_item_id"]
            isOneToOne: false
            referencedRelation: "budget_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "labor_line_items_contractor_id_fkey"
            columns: ["contractor_id"]
            isOneToOne: false
            referencedRelation: "contractors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "labor_line_items_payroll_period_id_fkey"
            columns: ["payroll_period_id"]
            isOneToOne: false
            referencedRelation: "payroll_periods"
            referencedColumns: ["id"]
          },
        ]
      }
      loan_deductions: {
        Row: {
          amount: number
          contractor_id: string
          created_at: string | null
          id: string
          loan_id: string
          payroll_period_id: string
        }
        Insert: {
          amount?: number
          contractor_id: string
          created_at?: string | null
          id?: string
          loan_id: string
          payroll_period_id: string
        }
        Update: {
          amount?: number
          contractor_id?: string
          created_at?: string | null
          id?: string
          loan_id?: string
          payroll_period_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "loan_deductions_contractor_id_fkey"
            columns: ["contractor_id"]
            isOneToOne: false
            referencedRelation: "contractors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "loan_deductions_loan_id_fkey"
            columns: ["loan_id"]
            isOneToOne: false
            referencedRelation: "contractor_loans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "loan_deductions_payroll_period_id_fkey"
            columns: ["payroll_period_id"]
            isOneToOne: false
            referencedRelation: "payroll_periods"
            referencedColumns: ["id"]
          },
        ]
      }
      material_invoices: {
        Row: {
          amount: number
          attachment_path: string | null
          budget_category_id: string | null
          budget_item_id: string | null
          description: string
          id: string
          invoice_reference: string | null
          notes: string | null
          payroll_period_id: string
          supplier_id: string
        }
        Insert: {
          amount?: number
          attachment_path?: string | null
          budget_category_id?: string | null
          budget_item_id?: string | null
          description: string
          id?: string
          invoice_reference?: string | null
          notes?: string | null
          payroll_period_id: string
          supplier_id: string
        }
        Update: {
          amount?: number
          attachment_path?: string | null
          budget_category_id?: string | null
          budget_item_id?: string | null
          description?: string
          id?: string
          invoice_reference?: string | null
          notes?: string | null
          payroll_period_id?: string
          supplier_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "material_invoices_budget_category_id_fkey"
            columns: ["budget_category_id"]
            isOneToOne: false
            referencedRelation: "budget_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "material_invoices_budget_item_id_fkey"
            columns: ["budget_item_id"]
            isOneToOne: false
            referencedRelation: "budget_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "material_invoices_payroll_period_id_fkey"
            columns: ["payroll_period_id"]
            isOneToOne: false
            referencedRelation: "payroll_periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "material_invoices_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      materials_catalog: {
        Row: {
          category: string | null
          code: string
          created_at: string
          default_min_stock: number
          description: string
          id: string
          is_active: boolean
          notes: string | null
          unit: string
          updated_at: string
        }
        Insert: {
          category?: string | null
          code: string
          created_at?: string
          default_min_stock?: number
          description: string
          id?: string
          is_active?: boolean
          notes?: string | null
          unit: string
          updated_at?: string
        }
        Update: {
          category?: string | null
          code?: string
          created_at?: string
          default_min_stock?: number
          description?: string
          id?: string
          is_active?: boolean
          notes?: string | null
          unit?: string
          updated_at?: string
        }
        Relationships: []
      }
      mercado_budget_lines: {
        Row: {
          agreed_quantity: number | null
          agreed_unit_price: number | null
          budget_id: string
          budgeted_quantity: number
          budgeted_total: number
          budgeted_unit_price: number
          category: string
          code: string | null
          contract_id: string | null
          description: string
          id: string
          sort_order: number
          unit: string
        }
        Insert: {
          agreed_quantity?: number | null
          agreed_unit_price?: number | null
          budget_id: string
          budgeted_quantity?: number
          budgeted_total?: number
          budgeted_unit_price?: number
          category: string
          code?: string | null
          contract_id?: string | null
          description: string
          id?: string
          sort_order?: number
          unit: string
        }
        Update: {
          agreed_quantity?: number | null
          agreed_unit_price?: number | null
          budget_id?: string
          budgeted_quantity?: number
          budgeted_total?: number
          budgeted_unit_price?: number
          category?: string
          code?: string | null
          contract_id?: string | null
          description?: string
          id?: string
          sort_order?: number
          unit?: string
        }
        Relationships: [
          {
            foreignKeyName: "mercado_budget_lines_budget_id_fkey"
            columns: ["budget_id"]
            isOneToOne: false
            referencedRelation: "mercado_budgets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mercado_budget_lines_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "adjustment_contracts"
            referencedColumns: ["id"]
          },
        ]
      }
      mercado_budgets: {
        Row: {
          file_name: string
          id: string
          imported_at: string
          project_id: string
          total_ajustes: number
          total_equipos: number
          total_mano_obra: number
          total_materiales: number
        }
        Insert: {
          file_name: string
          id?: string
          imported_at?: string
          project_id: string
          total_ajustes?: number
          total_equipos?: number
          total_mano_obra?: number
          total_materiales?: number
        }
        Update: {
          file_name?: string
          id?: string
          imported_at?: string
          project_id?: string
          total_ajustes?: number
          total_equipos?: number
          total_mano_obra?: number
          total_materiales?: number
        }
        Relationships: [
          {
            foreignKeyName: "mercado_budgets_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      partida_progress: {
        Row: {
          budget_category_id: string | null
          budget_item_id: string | null
          created_at: string
          cut_date: string
          executed_percent: number | null
          executed_quantity: number | null
          id: string
          notes: string | null
          project_id: string
          responsible: string | null
        }
        Insert: {
          budget_category_id?: string | null
          budget_item_id?: string | null
          created_at?: string
          cut_date: string
          executed_percent?: number | null
          executed_quantity?: number | null
          id?: string
          notes?: string | null
          project_id: string
          responsible?: string | null
        }
        Update: {
          budget_category_id?: string | null
          budget_item_id?: string | null
          created_at?: string
          cut_date?: string
          executed_percent?: number | null
          executed_quantity?: number | null
          id?: string
          notes?: string | null
          project_id?: string
          responsible?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "partida_progress_budget_category_id_fkey"
            columns: ["budget_category_id"]
            isOneToOne: false
            referencedRelation: "budget_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partida_progress_budget_item_id_fkey"
            columns: ["budget_item_id"]
            isOneToOne: false
            referencedRelation: "budget_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partida_progress_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_distributions: {
        Row: {
          amount: number
          bank_account: string | null
          bank_account_id: string | null
          bank_name: string | null
          beneficiary: string | null
          beneficiary_id: string | null
          beneficiary_type: string | null
          check_number: string | null
          completed_at: string | null
          id: string
          instructions: string | null
          payment_method: string
          payroll_period_id: string
          status: string
        }
        Insert: {
          amount?: number
          bank_account?: string | null
          bank_account_id?: string | null
          bank_name?: string | null
          beneficiary?: string | null
          beneficiary_id?: string | null
          beneficiary_type?: string | null
          check_number?: string | null
          completed_at?: string | null
          id?: string
          instructions?: string | null
          payment_method: string
          payroll_period_id: string
          status?: string
        }
        Update: {
          amount?: number
          bank_account?: string | null
          bank_account_id?: string | null
          bank_name?: string | null
          beneficiary?: string | null
          beneficiary_id?: string | null
          beneficiary_type?: string | null
          check_number?: string | null
          completed_at?: string | null
          id?: string
          instructions?: string | null
          payment_method?: string
          payroll_period_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_distributions_bank_account_id_fkey"
            columns: ["bank_account_id"]
            isOneToOne: false
            referencedRelation: "bank_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payment_distributions_payroll_period_id_fkey"
            columns: ["payroll_period_id"]
            isOneToOne: false
            referencedRelation: "payroll_periods"
            referencedColumns: ["id"]
          },
        ]
      }
      payroll_periods: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          created_at: string | null
          grand_total: number
          id: string
          notes: string | null
          period_number: number
          project_id: string
          report_date: string
          reported_by: string | null
          status: string
          total_indirect: number
          total_labor: number
          total_materials: number
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          grand_total?: number
          id?: string
          notes?: string | null
          period_number: number
          project_id: string
          report_date: string
          reported_by?: string | null
          status?: string
          total_indirect?: number
          total_labor?: number
          total_materials?: number
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          grand_total?: number
          id?: string
          notes?: string | null
          period_number?: number
          project_id?: string
          report_date?: string
          reported_by?: string | null
          status?: string
          total_indirect?: number
          total_labor?: number
          total_materials?: number
        }
        Relationships: [
          {
            foreignKeyName: "payroll_periods_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      price_list_items: {
        Row: {
          category: string
          code: string | null
          description: string
          id: string
          project_id: string
          unit: string
          unit_price: number
        }
        Insert: {
          category: string
          code?: string | null
          description: string
          id?: string
          project_id: string
          unit: string
          unit_price?: number
        }
        Update: {
          category?: string
          code?: string | null
          description?: string
          id?: string
          project_id?: string
          unit?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "price_list_items_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_members: {
        Row: {
          created_at: string
          id: string
          project_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          project_id: string
          role: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          project_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_members_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          admin_percent: number
          code: string
          company_id: string | null
          created_at: string | null
          created_by: string | null
          custom_indirects: Json
          dt_percent: number
          id: string
          location: string | null
          name: string
          planning_fee: number
          status: string
          transport_percent: number
          updated_at: string | null
        }
        Insert: {
          admin_percent?: number
          code: string
          company_id?: string | null
          created_at?: string | null
          created_by?: string | null
          custom_indirects?: Json
          dt_percent?: number
          id?: string
          location?: string | null
          name: string
          planning_fee?: number
          status?: string
          transport_percent?: number
          updated_at?: string | null
        }
        Update: {
          admin_percent?: number
          code?: string
          company_id?: string | null
          created_at?: string | null
          created_by?: string | null
          custom_indirects?: Json
          dt_percent?: number
          id?: string
          location?: string | null
          name?: string
          planning_fee?: number
          status?: string
          transport_percent?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "projects_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projects_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_order_items: {
        Row: {
          description: string
          id: string
          purchase_order_id: string
          quantity: number
          subtotal: number
          unit: string
          unit_price: number
        }
        Insert: {
          description: string
          id?: string
          purchase_order_id: string
          quantity: number
          subtotal: number
          unit: string
          unit_price: number
        }
        Update: {
          description?: string
          id?: string
          purchase_order_id?: string
          quantity?: number
          subtotal?: number
          unit?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "purchase_order_items_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_orders: {
        Row: {
          approval_code: string | null
          approved_at: string | null
          approved_by: string | null
          created_at: string | null
          id: string
          notes: string | null
          order_number: string
          project_id: string | null
          rejection_reason: string | null
          requested_by: string
          requested_date: string
          required_date: string | null
          signature_data: string | null
          status: string
          subtotal: number
          supplier_id: string | null
          tax_percent: number
          total: number
          updated_at: string | null
        }
        Insert: {
          approval_code?: string | null
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          id?: string
          notes?: string | null
          order_number: string
          project_id?: string | null
          rejection_reason?: string | null
          requested_by: string
          requested_date?: string
          required_date?: string | null
          signature_data?: string | null
          status?: string
          subtotal?: number
          supplier_id?: string | null
          tax_percent?: number
          total?: number
          updated_at?: string | null
        }
        Update: {
          approval_code?: string | null
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          id?: string
          notes?: string | null
          order_number?: string
          project_id?: string | null
          rejection_reason?: string | null
          requested_by?: string
          requested_date?: string
          required_date?: string | null
          signature_data?: string | null
          status?: string
          subtotal?: number
          supplier_id?: string | null
          tax_percent?: number
          total?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "purchase_orders_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_quote_items: {
        Row: {
          description: string
          id: string
          quantity: number
          quote_id: string
          subtotal: number
          unit: string
          unit_price: number
        }
        Insert: {
          description: string
          id?: string
          quantity?: number
          quote_id: string
          subtotal?: number
          unit: string
          unit_price?: number
        }
        Update: {
          description?: string
          id?: string
          quantity?: number
          quote_id?: string
          subtotal?: number
          unit?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "purchase_quote_items_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "purchase_quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_quotes: {
        Row: {
          attachment_path: string | null
          id: string
          negotiated_notes: string | null
          negotiated_total: number | null
          notes: string | null
          quote_number: string | null
          requisition_id: string
          subtotal: number
          supplier_id: string
          tax_percent: number
          total: number
          valid_until: string | null
        }
        Insert: {
          attachment_path?: string | null
          id?: string
          negotiated_notes?: string | null
          negotiated_total?: number | null
          notes?: string | null
          quote_number?: string | null
          requisition_id: string
          subtotal?: number
          supplier_id: string
          tax_percent?: number
          total?: number
          valid_until?: string | null
        }
        Update: {
          attachment_path?: string | null
          id?: string
          negotiated_notes?: string | null
          negotiated_total?: number | null
          notes?: string | null
          quote_number?: string | null
          requisition_id?: string
          subtotal?: number
          supplier_id?: string
          tax_percent?: number
          total?: number
          valid_until?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "purchase_quotes_requisition_id_fkey"
            columns: ["requisition_id"]
            isOneToOne: false
            referencedRelation: "purchase_requisitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_quotes_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_requisitions: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          approved_quote_id: string | null
          available_quantity_at_request: number | null
          budget_category_id: string | null
          budget_item_id: string | null
          created_at: string | null
          description: string
          excess_motivo: string | null
          id: string
          notes: string | null
          ordered_at: string | null
          payment_type: string | null
          planned_quantity_at_request: number | null
          project_id: string
          quantity_requested: number | null
          received_at: string | null
          received_by: string | null
          rejection_reason: string | null
          released_at: string | null
          released_by: string | null
          req_number: string
          requested_by: string
          required_date: string | null
          resource_type: string | null
          revision_notes: string | null
          signature_data: string | null
          single_quote_justification: string | null
          status: string
          unit: string | null
          updated_at: string | null
          validated_at: string | null
          validated_by: string | null
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          approved_quote_id?: string | null
          available_quantity_at_request?: number | null
          budget_category_id?: string | null
          budget_item_id?: string | null
          created_at?: string | null
          description: string
          excess_motivo?: string | null
          id?: string
          notes?: string | null
          ordered_at?: string | null
          payment_type?: string | null
          planned_quantity_at_request?: number | null
          project_id: string
          quantity_requested?: number | null
          received_at?: string | null
          received_by?: string | null
          rejection_reason?: string | null
          released_at?: string | null
          released_by?: string | null
          req_number: string
          requested_by: string
          required_date?: string | null
          resource_type?: string | null
          revision_notes?: string | null
          signature_data?: string | null
          single_quote_justification?: string | null
          status?: string
          unit?: string | null
          updated_at?: string | null
          validated_at?: string | null
          validated_by?: string | null
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          approved_quote_id?: string | null
          available_quantity_at_request?: number | null
          budget_category_id?: string | null
          budget_item_id?: string | null
          created_at?: string | null
          description?: string
          excess_motivo?: string | null
          id?: string
          notes?: string | null
          ordered_at?: string | null
          payment_type?: string | null
          planned_quantity_at_request?: number | null
          project_id?: string
          quantity_requested?: number | null
          received_at?: string | null
          received_by?: string | null
          rejection_reason?: string | null
          released_at?: string | null
          released_by?: string | null
          req_number?: string
          requested_by?: string
          required_date?: string | null
          resource_type?: string | null
          revision_notes?: string | null
          signature_data?: string | null
          single_quote_justification?: string | null
          status?: string
          unit?: string | null
          updated_at?: string | null
          validated_at?: string | null
          validated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "purchase_requisitions_budget_category_id_fkey"
            columns: ["budget_category_id"]
            isOneToOne: false
            referencedRelation: "budget_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_requisitions_budget_item_id_fkey"
            columns: ["budget_item_id"]
            isOneToOne: false
            referencedRelation: "budget_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_requisitions_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          display_name: string | null
          endpoint: string
          id: string
          last_seen_at: string
          p256dh: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          display_name?: string | null
          endpoint: string
          id?: string
          last_seen_at?: string
          p256dh: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          display_name?: string | null
          endpoint?: string
          id?: string
          last_seen_at?: string
          p256dh?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: []
      }
      quality_control: {
        Row: {
          actual_resistance: number | null
          concrete_supplier: string | null
          element: string
          expected_resistance: number | null
          id: string
          laboratory: string | null
          notes: string | null
          pour_date: string
          project_id: string
          status: string | null
          test_age: string | null
          test_date: string | null
        }
        Insert: {
          actual_resistance?: number | null
          concrete_supplier?: string | null
          element: string
          expected_resistance?: number | null
          id?: string
          laboratory?: string | null
          notes?: string | null
          pour_date: string
          project_id: string
          status?: string | null
          test_age?: string | null
          test_date?: string | null
        }
        Update: {
          actual_resistance?: number | null
          concrete_supplier?: string | null
          element?: string
          expected_resistance?: number | null
          id?: string
          laboratory?: string | null
          notes?: string | null
          pour_date?: string
          project_id?: string
          status?: string | null
          test_age?: string | null
          test_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quality_control_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      role_capabilities: {
        Row: {
          capability_id: string
          role_id: string
        }
        Insert: {
          capability_id: string
          role_id: string
        }
        Update: {
          capability_id?: string
          role_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "role_capabilities_capability_id_fkey"
            columns: ["capability_id"]
            isOneToOne: false
            referencedRelation: "capabilities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "role_capabilities_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
        ]
      }
      roles: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_director: boolean
          is_system: boolean
          name: string
          slug: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_director?: boolean
          is_system?: boolean
          name: string
          slug: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_director?: boolean
          is_system?: boolean
          name?: string
          slug?: string
        }
        Relationships: []
      }
      schedule_tasks: {
        Row: {
          color: string
          created_at: string | null
          end_date: string
          id: string
          name: string
          notes: string | null
          progress: number
          project_id: string
          start_date: string
        }
        Insert: {
          color?: string
          created_at?: string | null
          end_date: string
          id?: string
          name: string
          notes?: string | null
          progress?: number
          project_id: string
          start_date: string
        }
        Update: {
          color?: string
          created_at?: string | null
          end_date?: string
          id?: string
          name?: string
          notes?: string | null
          progress?: number
          project_id?: string
          start_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "schedule_tasks_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      suppliers: {
        Row: {
          bank_account: string | null
          bank_name: string | null
          contact_phone: string | null
          created_at: string | null
          id: string
          is_active: boolean
          name: string
          payment_terms: string | null
          rnc: string | null
          updated_at: string | null
        }
        Insert: {
          bank_account?: string | null
          bank_name?: string | null
          contact_phone?: string | null
          created_at?: string | null
          id?: string
          is_active?: boolean
          name: string
          payment_terms?: string | null
          rnc?: string | null
          updated_at?: string | null
        }
        Update: {
          bank_account?: string | null
          bank_name?: string | null
          contact_phone?: string | null
          created_at?: string | null
          id?: string
          is_active?: boolean
          name?: string
          payment_terms?: string | null
          rnc?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      transactions: {
        Row: {
          bank: string | null
          budget_category_id: string | null
          cashed_date: string | null
          check_number: string | null
          created_at: string | null
          date: string
          description: string
          due_date: string | null
          id: string
          invoice_number: string | null
          notes: string | null
          payment_condition: string | null
          payroll_period_id: string | null
          project_id: string
          quantity: number | null
          supplier_id: string | null
          total: number
          unit_price: number | null
        }
        Insert: {
          bank?: string | null
          budget_category_id?: string | null
          cashed_date?: string | null
          check_number?: string | null
          created_at?: string | null
          date: string
          description: string
          due_date?: string | null
          id?: string
          invoice_number?: string | null
          notes?: string | null
          payment_condition?: string | null
          payroll_period_id?: string | null
          project_id: string
          quantity?: number | null
          supplier_id?: string | null
          total?: number
          unit_price?: number | null
        }
        Update: {
          bank?: string | null
          budget_category_id?: string | null
          cashed_date?: string | null
          check_number?: string | null
          created_at?: string | null
          date?: string
          description?: string
          due_date?: string | null
          id?: string
          invoice_number?: string | null
          notes?: string | null
          payment_condition?: string | null
          payroll_period_id?: string | null
          project_id?: string
          quantity?: number | null
          supplier_id?: string | null
          total?: number
          unit_price?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_budget_category_id_fkey"
            columns: ["budget_category_id"]
            isOneToOne: false
            referencedRelation: "budget_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_payroll_period_id_fkey"
            columns: ["payroll_period_id"]
            isOneToOne: false
            referencedRelation: "payroll_periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      user_documents: {
        Row: {
          display_name: string | null
          doc_type: string
          file_path: string
          id: string
          uploaded_at: string
          user_id: string
        }
        Insert: {
          display_name?: string | null
          doc_type: string
          file_path: string
          id?: string
          uploaded_at?: string
          user_id: string
        }
        Update: {
          display_name?: string | null
          doc_type?: string
          file_path?: string
          id?: string
          uploaded_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_documents_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          bank_account_id: string | null
          cedula: string | null
          created_at: string
          display_name: string
          email: string | null
          first_name: string | null
          hire_date: string | null
          id: string
          is_active: boolean
          is_director: boolean
          job_title: string | null
          last_name: string | null
          passport: string | null
          payment_terms: string | null
          phone: string | null
          salary: number | null
          updated_at: string
        }
        Insert: {
          bank_account_id?: string | null
          cedula?: string | null
          created_at?: string
          display_name: string
          email?: string | null
          first_name?: string | null
          hire_date?: string | null
          id: string
          is_active?: boolean
          is_director?: boolean
          job_title?: string | null
          last_name?: string | null
          passport?: string | null
          payment_terms?: string | null
          phone?: string | null
          salary?: number | null
          updated_at?: string
        }
        Update: {
          bank_account_id?: string | null
          cedula?: string | null
          created_at?: string
          display_name?: string
          email?: string | null
          first_name?: string | null
          hire_date?: string | null
          id?: string
          is_active?: boolean
          is_director?: boolean
          job_title?: string | null
          last_name?: string | null
          passport?: string | null
          payment_terms?: string | null
          phone?: string | null
          salary?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_profiles_bank_account_id_fkey"
            columns: ["bank_account_id"]
            isOneToOne: false
            referencedRelation: "bank_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _project_of_budget_category: { Args: { p_id: string }; Returns: string }
      _project_of_contract: { Args: { p_id: string }; Returns: string }
      _project_of_mercado_budget: { Args: { p_id: string }; Returns: string }
      _project_of_payroll: { Args: { p_id: string }; Returns: string }
      _project_of_purchase_order: { Args: { p_id: string }; Returns: string }
      _project_of_quote: { Args: { p_id: string }; Returns: string }
      _project_of_requisition: { Args: { p_id: string }; Returns: string }
      current_user_can_access_project: {
        Args: { p_project_id: string }
        Returns: boolean
      }
      current_user_has_role: {
        Args: { p_project_id: string; p_roles: string[] }
        Returns: boolean
      }
      current_user_is_director: { Args: never; Returns: boolean }
      is_member_of_project: { Args: { p_project_id: string }; Returns: boolean }
      user_app_capabilities: {
        Args: never
        Returns: {
          capability_slug: string
        }[]
      }
      user_companies: {
        Args: never
        Returns: {
          company_id: string
        }[]
      }
      user_has_any_capability: {
        Args: { p_capabilities: string[]; p_project_id: string }
        Returns: boolean
      }
      user_has_any_role_anywhere: {
        Args: { p_roles: string[] }
        Returns: boolean
      }
      user_has_capability: {
        Args: { p_capability: string; p_project_id: string }
        Returns: boolean
      }
      user_has_capability_anywhere: {
        Args: { p_capability: string }
        Returns: boolean
      }
      user_has_project_role: {
        Args: { p_project_id: string; p_roles: string[] }
        Returns: boolean
      }
      user_project_capabilities: {
        Args: { p_project_id: string }
        Returns: {
          capability_slug: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
